name: PROJETO GCS - by Slmm

on: [push]
      
jobs:
  
  Projeto_Final:
      permissions: write-all
      runs-on: ubuntu-latest
      
      strategy:
       matrix:
        node-version: [18.x]
        
      steps:
         - uses: actions/checkout@v3
         - name: Use node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
             node-version: ${{ matrix.node-version }}
         - run: npm ci
         - run: npm run build --if-present
         - run: npm test
         - name: Teste Report
           uses: dorny/test-reporter@v1
           if: success() || failure()  # roda de qualquer maneira
           with:
            name: JEST tests
            path: reports/jest-*.xml
            reporter: jest-junit
            
         # https://geode-ink-activity.glitch.me/
         - name: Enviando ao Glich
           uses: kanadgupta/glitch-sync@main
           with:
              auth-token: '${{ secrets.authToken }}'
              project-id: '${{ secrets.projectId }}'
              #path: 'dist' # optional  
